export const FETCH_USER = "FETCH_USER";
export const CUR_LOCATION = "CUR_LOCATION";
export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_HOSTS = "FETCH_HOSTS";
export const ADD_HOST = "ADD_HOST";
export const ADD_EVENT = "ADD_EVENT";
export const TOGGLE_HOST_INTEREST = "TOGGLE_HOST_INTEREST";
export const TOGGLE_EVENT_INTEREST = "TOGGLE_EVENT_INTEREST";
